---
language: ruby
sudo: false
cache: bundler
gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.1
script: bundle exec rake spec
